'use client';
import { useState } from 'react';
import { skillSummary, type SkillTrack } from '@/lib/ascension-index';
import { archetypeWeights, localDate, priorities, weekSummary, type ArchetypePlan, type Habit, type RoutineState } from '@/lib/routine';
import { HabitEditor } from './routine-workspace';
import './routine.css';
export function AscensionPlan({view,state,onChange,archetypes,ids,onIds,tracks,onView,onRoutine}:{view:string;state:RoutineState;onChange:(s:RoutineState)=>void;archetypes:ArchetypePlan[];ids:string[];onIds:(ids:string[])=>void;tracks:SkillTrack[];onView:(s:string)=>void;onRoutine:()=>void}) {
  const [editing,setEditing]=useState<Habit|null>(null);const [notice,setNotice]=useState('');const date=localDate();const weights=archetypeWeights(ids);const selected=weights.map(w=>({...archetypes.find(a=>a.id===w.id)!,weight:w.weight})).filter(a=>a.id);const plan=priorities(state,archetypes,ids,date,Object.fromEntries(tracks.map(t=>[t.id,skillSummary(t).level===null?0:1-(skillSummary(t).level??0)/150])));const weekly=weekSummary(state,date);
  const progress=(a:ArchetypePlan)=>a.milestones.length?Math.round(a.milestones.filter((_,i)=>state.goals[`${a.id}:${i}`]).length/a.milestones.length*100):0;
  const cards=<div className="ascension-summary-cards">{selected.map((a,i)=><article key={a.id}><small>{['Primário','Secundário','Terciário'][i]} · {Math.round(a.weight*100)}%</small><h3>{a.name}</h3><strong>{progress(a)}%</strong><progress aria-label={`Objetivos de ${a.name}`} value={progress(a)} max={100}/><small>Objetivos confirmados por você</small>{view==='archetypes'&&<ul>{a.milestones.slice(0,3).map(m=><li key={m}>{m}</li>)}</ul>}</article>)}</div>;
  return <section className="routine-area"><p role="status">{notice}</p>
    {view==='overview'&&<>{cards}<h3>Prioridades de hoje</h3>{plan.slice(0,3).map((r,i)=><div className="routine-row" key={r.habit.id}><strong>{i+1}. {r.habit.name}</strong><small>{r.habit.minutes} min</small></div>)}{!plan.length&&<p>Sem sugestões compatíveis com sua disponibilidade. Ajuste o plano ou selecione um arquétipo.</p>}<button className="routine-primary" onClick={()=>onView('plan')}>Ver plano</button><p>Esta semana: {weekly.done}/{weekly.target} atividades · {weekly.percent}% de execução.</p></>}
    {view==='archetypes'&&<><h3>Quem você quer se tornar?</h3><p>Use de um a três arquétipos. Com menos de três, os pesos são redistribuídos proporcionalmente.</p>{[0,1,2].map(i=><label key={i}>{['Primário','Secundário','Terciário'][i]}<select value={ids[i]??''} onChange={e=>{const next=[...ids];next[i]=e.target.value;if(i===1&&!e.target.value)next[2]='';onIds(next);}} disabled={i===2&&!ids[1]}>{i>0&&<option value="">Não utilizar</option>}{archetypes.filter(a=>!ids.includes(a.id)||ids[i]===a.id).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}{cards}</>}
    {view==='goals'&&<>{selected.map(a=><section key={a.id}><h3>{a.name} · {progress(a)}%</h3>{a.milestones.map((m,i)=><label className="routine-check" key={i}><input type="checkbox" checked={Boolean(state.goals[`${a.id}:${i}`])} onChange={e=>onChange({...state,goals:{...state.goals,[`${a.id}:${i}`]:e.target.checked}})}/>{m}</label>)}</section>)}<p className="routine-muted">Confirmar um objetivo não altera automaticamente seu nível técnico.</p></>}
    {view==='plan'&&<><header className="routine-heading"><h3>Seu plano de hoje</h3><button onClick={onRoutine}>Abrir rotina</button></header><div className="routine-fields"><label>Tempo disponível (min)<input type="number" min="0" max="1440" value={state.minutes} onChange={e=>onChange({...state,minutes:Math.min(1440,Math.max(0,Number(e.target.value)))})}/></label><label className="routine-check"><input type="checkbox" checked={state.recovery} onChange={e=>onChange({...state,recovery:e.target.checked})}/> Hoje é recuperação física</label></div><p className="routine-muted">Sugestões calculadas a partir dos protocolos existentes, pesos, objetivos pendentes e histórico. Revise a duração e marque atividades físicas antes de adicionar.</p>{plan.map((r,i)=><article className="ascension-plan-row" key={r.habit.id}><small>{i<3?`Prioridade ${i+1}`:'Complementar'} · {r.habit.minutes} min</small><h3>{r.habit.name}</h3><p>{r.habit.contributions.map(c=>archetypes.find(a=>a.id===c.id)?.name).filter(Boolean).join(' · ')}</p><details><summary>Por que isso é prioridade?</summary><p>{r.reason}</p></details><div className="routine-chips"><button className="routine-primary" onClick={()=>setEditing(r.habit)}>{state.habits.some(h=>h.id===r.habit.id)?'Editar na rotina':'Adicionar à rotina'}</button><button onClick={()=>setEditing({...r.habit,name:'',id:crypto.randomUUID()})}>Trocar</button><button onClick={()=>{onChange({...state,dismissed:[...state.dismissed,`${date}:${r.habit.id}`]});setNotice('Sugestão removida de hoje.');}}>Remover de hoje</button></div></article>)}{!plan.length&&<p>Nenhuma atividade pendente cabe no tempo disponível.</p>}</>}
    {editing&&<HabitEditor habit={editing} tracks={tracks} archetypes={selected} onClose={()=>setEditing(null)} onSave={h=>{const existing=state.habits.find(a=>a.id===h.id);onChange({...state,habits:existing?state.habits.map(a=>a.id===h.id?h:a):[...state.habits,{...h,id:h.id.startsWith('suggestion:')?crypto.randomUUID():h.id}]});setEditing(null);setNotice('Atividade salva na Rotina.');}}/>}
  </section>;
}
