'use client';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import dynamic from 'next/dynamic';
import { avatarBeardStyles, avatarHairStyles, avatarItemEquivalent, avatarItemName, avatarItems, initialAppearance, parseAvatarDescription, type Appearance, type AvatarAccount, type AvatarStyleMode } from '@/lib/avatar';
import { readApiResponse } from '@/lib/api-contract';
import AvatarPhotoCreator from './avatar-photo-creator';
import AvatarFaceControls from './avatar-face-controls';
import './avatar.css';
const Scene=dynamic(()=>import('./avatar-scene'),{ssr:false,loading:()=> <div className="avatar-canvas avatar-loading">Preparando avatar 3D…</div>});
const sections=['Visão Geral','Equipar','Loja','Evolução','Criar por Foto','Histórico'] as const;
const appearanceSections=['Rosto','Cabelo','Corpo','Cores','Prévia'] as const;
export default function AvatarWorkspace(){
 const [compare,setCompare]=useState(false);
 const [styleMode,setStyleMode]=useState<AvatarStyleMode>('rpg');
 const [description,setDescription]=useState(''); const [historyCount,setHistoryCount]=useState(20);const [category,setCategory]=useState('Todas');const [ownership,setOwnership]=useState('Todos');const [sort,setSort]=useState('Menor preço');
 const [account,setAccount]=useState<AvatarAccount|null>(null);const [draft,setDraft]=useState<Appearance>(initialAppearance);const [section,setSection]=useState<typeof sections[number]>('Visão Geral');const [appearanceSection,setAppearanceSection]=useState<typeof appearanceSections[number]>('Rosto');const [focus,setFocus]=useState<'corpo'|'rosto'>('corpo');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [preview,setPreview]=useState<string|null>(null);const [rarity,setRarity]=useState('Todas');const [snapshot,setSnapshot]=useState<number|null>(null);
 const load=useCallback(async()=>{try{const data=await readApiResponse<AvatarAccount>(await fetch('/api/avatar'));setError('');setAccount(data);setDraft(data.appearance);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar.');}},[]);
 useEffect(()=>{const abort=new AbortController();fetch('/api/avatar',{signal:abort.signal}).then(response=>readApiResponse<AvatarAccount>(response)).then(data=>{setAccount(data);setDraft(data.appearance);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível carregar.');});return()=>abort.abort();},[]);
 async function action(body:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setMessage('');try{const data=await readApiResponse<AvatarAccount>(await fetch('/api/avatar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));setAccount(data);setMessage(body.action==='sync'?'Atividades salvas conferidas.':'Salvo.');setPreview(null);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 const shown=snapshot!==null&&account?.history[snapshot]?account.history[snapshot].appearance:section==='Evolução'||section==='Criar por Foto'?draft:account?.appearance||draft;
 const item=avatarItems.find(i=>i.id===preview);const equipment=useMemo(()=>{const e={...account?.equipped};if(item)e[item.slot]=item.id;return e;},[account?.equipped,item]);
 const changeStyle=(mode:AvatarStyleMode)=>setStyleMode(mode);
 return <section className="avatar-workspace"><header><div><span className="eyebrow">IDENTIDADE EM EVOLUÇÃO</span><h2>Seu avatar</h2><p>Seu percurso, em uma nova dimensão.</p></div><strong>{account?.balance??0} <small>Essência</small></strong></header>
 <nav aria-label="Seções do avatar">{sections.map(s=><button key={s} aria-current={section===s?'page':undefined} onClick={()=>{setSection(s);setCompare(false);if(s==='Criar por Foto')setFocus('rosto');setSnapshot(null);setPreview(null);}}>{s}</button>)}</nav>
 <section className="avatar-style-switch" aria-label="Estilo do personagem"><div><span className="eyebrow">DUAS IDENTIDADES, UMA CONQUISTA</span><strong>{styleMode==='rpg'?'Herói RPG':'Versão humana'}</strong><small>{styleMode==='rpg'?'Relíquias, mantos e armaduras':'Casual, esporte e alfaiataria premium'}</small></div><div><button aria-pressed={styleMode==='rpg'} onClick={()=>changeStyle('rpg')}>RPG</button><button aria-pressed={styleMode==='human'} onClick={()=>changeStyle('human')}>Humano</button></div></section>
 {error&&<div role="alert" className="avatar-error">{error}<button onClick={()=>void load()}>Atualizar</button></div>}{message&&<p role="status">{message}</p>}
 <div className="avatar-layout"><div className={`avatar-stage ${styleMode==='rpg'?'rpg-stage':'human-stage'}`}><div className="avatar-stage-glow"/><Scene appearance={compare&&account?account.appearance:shown} equipped={equipment} archetypes={account?.evidence?.summary.archetypes} physicalDays={snapshot===null?account?.evidence?.physicalDays.length:0} focus={focus} styleMode={styleMode}/>{equipment["título"]&&<strong className="avatar-equipped-title">{avatarItems.find(i=>i.id===equipment["título"])?.name}</strong>}<div className="avatar-stage-tools"><button type="button" aria-pressed={focus==='rosto'} onClick={()=>setFocus(f=>f==='rosto'?'corpo':'rosto')}>{focus==='rosto'?'Ver corpo':'Ver rosto'}</button>{account&&(section==='Evolução'||section==='Criar por Foto')&&<button type="button" aria-pressed={compare} onClick={()=>setCompare(v=>!v)}>{compare?'Ver depois (ajustes)':'Ver antes (salvo)'}</button>}</div><p>{compare?'Antes • aparência salva':snapshot!==null?'Registro histórico':item?`Prévia • ${avatarItemName(item,styleMode)}`:styleMode==='rpg'?'Personagem RPG • inventário e relíquias':'Personagem humano • estilo real equivalente'}</p>{item&&<button onClick={()=>setPreview(null)}>Encerrar prévia</button>}</div><div className="avatar-details">
 {!account&&!error&&<p role="status">Carregando seu perfil…</p>}
 {account&&section==='Visão Geral'&&<><h3>{account.days.length>=100?'Ascendente':account.days.length>=21?'Consistente':'Em construção'}</h3><p>{account.days.length} dias ativos observados desde a criação do avatar.</p><button className="primary-button" onClick={()=>setSection('Evolução')}>Personalizar meu avatar</button><h3>Seu percurso</h3><p>{account.evidence?.summary.archetypes.map(id=>({sage:"Sábio",athlete:"Atleta",entrepreneur:"Empreendedor",leader:"Líder",executor:"Executor",strategist:"Estrategista"}[id]||id)).join(" · ")||"Escolha seus arquétipos na Ascensão."}</p><p>Domínio de estudo: {account.evidence?.summary.mastery??"—"}% · {account.evidence?.summary.studiedConcepts??0} conceitos avaliados</p>{account.evidence?.summary.skills.map((skill,index)=><div className="avatar-row" key={`${skill.name}:${index}`}><span>{skill.name}</span><strong>{skill.level===null?"Sem avaliação":`Nível pessoal ${skill.level}`}</strong></div>)}<h3>Seu próximo marco</h3><p>Complete a Rotina, responda no modo Domínio ou registre resultados nas Habilidades. Os marcos são atualizados após salvar o painel. Abrir o aplicativo não gera Essência.</p><button disabled={busy} onClick={()=>action({action:'sync'})}>{busy?'Conferindo…':'Conferir minha atividade de hoje'}</button><p className="avatar-note">Dias anteriores à criação não são creditados. Os registros são autodeclarados; não representam certificação de desempenho físico.</p><details className="avatar-missions"><summary>Missões e recompensas</summary><h3>Missões de domínio</h3><div className="avatar-row"><span>30 dias com 10 questões distintas no modo Domínio e 80% de acertos</span><strong>{account.evidence?.studyDays.length||0}/30</strong></div><div className="avatar-row"><span>30 dias de melhora física documentada, comparada a registros separados por 14 dias</span><strong>{account.evidence?.physicalDays.length||0}/30</strong></div><p className="avatar-note">Os marcos de 7, 30 e 100 dias por missão concedem 30, 100 e 200 Essências, uma vez cada.</p><h3>Conquistas de constância</h3>{[7,21,30,60,100,180,365,730].map(n=><div className="avatar-row" key={n}><span>{n} dias ativos</span><strong>{account.days.length>=n?'Conquistado':`${account.days.length} / ${n}`}</strong></div>)}</details></>}
 {account&&section==='Equipar'&&<>
  <div className="inventory-heading"><div><span className="eyebrow">INVENTÁRIO COMPARTILHADO</span><h3>Equipamento do personagem</h3><p>Cada conquista libera a relíquia RPG e sua versão humana equivalente.</p></div><strong>{account.inventory.length}<small>itens obtidos</small></strong></div>
  <div className="equipment-slots" aria-label="Equipamentos atuais">{['cabeça','tronco','mão','calçados','insígnia','aura'].map(slot=>{const equippedItem=avatarItems.find(candidate=>candidate.id===account.equipped[slot]);return <article key={slot} className={equippedItem?'filled':''}><small>{slot}</small><strong>{equippedItem?avatarItemName(equippedItem,styleMode):'Vazio'}</strong>{equippedItem&&<span>{avatarItemEquivalent(equippedItem,styleMode)}</span>}</article>;})}</div>
  <div className="avatar-item-grid">{avatarItems.filter(i=>account.inventory.includes(i.id)).map(i=><article className="avatar-item" data-rarity={i.rarity} key={i.id}><span className={`avatar-item-preview preview-${styleMode}`} style={{'--item-color':i.color} as React.CSSProperties}/><span className="item-mode-badge">{styleMode==='rpg'?'RELÍQUIA':'REAL'}</span><strong>{avatarItemName(i,styleMode)}</strong><small>{i.slot} · {i.rarity}</small><p className="item-equivalent">Equivale a: <b>{avatarItemEquivalent(i,styleMode)}</b></p><div><button onClick={()=>setPreview(i.id)}>Visualizar</button><button disabled={busy||account.equipped[i.slot]===i.id} onClick={()=>action({action:'equip',id:i.id})}>{account.equipped[i.slot]===i.id?'Equipado':'Equipar'}</button>{account.equipped[i.slot]===i.id&&i.slot!=='tronco'&&<button disabled={busy} onClick={()=>action({action:'unequip',slot:i.slot})}>Remover</button>}</div></article>)}</div>
 </>}
 {account&&section==='Loja'&&<><div className="inventory-heading"><div><span className="eyebrow">ATELIÊ DE ASCENSÃO</span><h3>Relíquias com vida real</h3><p>Uma única conquista adiciona as duas versões ao seu inventário.</p></div></div><label>Raridade<select value={rarity} onChange={e=>setRarity(e.target.value)}><option>Todas</option>{[...new Set(avatarItems.map(i=>i.rarity))].map(r=><option key={r}>{r}</option>)}</select></label><div className="avatar-fields"><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option>Todas</option>{[...new Set(avatarItems.map(i=>i.slot))].map(v=><option key={v}>{v}</option>)}</select></label><label>Inventário<select value={ownership} onChange={e=>setOwnership(e.target.value)}>{["Todos","Adquiridos","Não adquiridos"].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Ordenar<select value={sort} onChange={e=>setSort(e.target.value)}><option>Menor preço</option><option>Maior preço</option></select></label><div className="avatar-item-grid">{avatarItems.filter(i=>i.price>0&&(rarity==='Todas'||rarity===i.rarity)&&(category==='Todas'||category===i.slot)&&(ownership==='Todos'||(ownership==='Adquiridos')===account.inventory.includes(i.id))).sort((a,b)=>sort==='Menor preço'?a.price-b.price:b.price-a.price).map(i=><article className="avatar-item" data-rarity={i.rarity} key={i.id}><span className={`avatar-item-preview preview-${styleMode}`} style={{'--item-color':i.color} as React.CSSProperties}/><span className="item-mode-badge">{styleMode==='rpg'?'RELÍQUIA':'REAL'}</span><strong>{avatarItemName(i,styleMode)}</strong><small>{i.rarity} · {i.slot}</small><p className="item-equivalent">Também libera: <b>{avatarItemEquivalent(i,styleMode)}</b></p><p>{i.price} Essência · {i.days} dias ativos observados</p>{["gold","aura","apex"].includes(i.id)&&<p>Também exige 30 dias de domínio e 30 dias de resultados físicos observados.</p>}<div><button onClick={()=>setPreview(i.id)}>Experimentar</button><button disabled={busy||account.inventory.includes(i.id)||account.balance<i.price||account.days.length<i.days} onClick={()=>{if(window.confirm(`Comprar ${avatarItemName(i,styleMode)} por ${i.price} Essência? O saldo será descontado.`))void action({action:'buy',id:i.id});}}>{account.inventory.includes(i.id)?'Adquirido':account.days.length<i.days?'Requisito pendente':account.balance<i.price?'Saldo insuficiente':'Comprar'}</button></div></article>)}</div><p className="avatar-note">Sem dinheiro real. Itens raros exigem saldo e tempo de atividade. O catálogo inicial prioriza escassez; preços não garantem um prazo de conquista.</p></>}
 {section==='Evolução'&&<form className="avatar-editor" onSubmit={e=>{e.preventDefault();void action({action:'appearance',appearance:draft});}}><div className="avatar-editor-heading"><div><h3>Personalização</h3><p>As alterações aparecem no avatar antes de salvar.</p></div><div className="avatar-focus"><button type="button" aria-pressed={focus==='rosto'} onClick={()=>setFocus('rosto')}>Rosto</button><button type="button" aria-pressed={focus==='corpo'} onClick={()=>setFocus('corpo')}>Corpo</button></div></div><div className="avatar-editor-tabs" role="tablist" aria-label="Partes do avatar">{appearanceSections.map(tab=><button type="button" role="tab" aria-selected={appearanceSection===tab} key={tab} onClick={()=>{setAppearanceSection(tab);setFocus(tab==='Rosto'||tab==='Cabelo'||tab==='Cores'?'rosto':'corpo');}}>{tab}</button>)}</div>
 {appearanceSection==='Rosto'&&<div role="tabpanel" className="avatar-panel"><h4>Traços do personagem</h4><label>Apresentação<select value={draft.shape} onChange={e=>setDraft({...draft,shape:e.target.value as Appearance['shape']})}>{['neutro','masculino','feminino'].map(v=><option key={v}>{v}</option>)}</select></label><label>Formato do rosto<select value={draft.face||'oval'} onChange={e=>setDraft({...draft,face:e.target.value as Appearance['face']})}>{['oval','angular','arredondado'].map(v=><option key={v}>{v}</option>)}</select></label><label>Barba<select value={draft.beardStyle??(draft.beard?'barba curta':'sem barba')} onChange={e=>{const beardStyle=e.target.value as Appearance['beardStyle'];setDraft({...draft,beardStyle,beard:beardStyle!=='sem barba'});}}>{avatarBeardStyles.map(value=><option key={value}>{value}</option>)}</select></label><p className="avatar-note">Olhos em camadas, mandíbula e expressão são renderizados em estilo anime adulto.</p><AvatarFaceControls appearance={draft} onChange={a=>{setCompare(false);setDraft(a);}}/></div>}
 {appearanceSection==='Cabelo'&&<div role="tabpanel" className="avatar-panel"><h4>Estilo e silhueta</h4><div className="avatar-options">{avatarHairStyles.map(value=><button type="button" aria-pressed={(draft.hair==='curto'?'moderno':draft.hair)===value} key={value} onClick={()=>setDraft({...draft,hair:value})}><span className={`hair-swatch hair-${value}`}/>{value}</button>)}</div><label>Comprimento do cabelo<input type="range" min="0.6" max="1.5" step="0.01" value={draft.hairLength??1} onChange={e=>{setCompare(false);setDraft({...draft,hairLength:Number(e.target.value)});}}/></label><label>Cor do cabelo<input type="color" value={draft.hairColor} onChange={e=>setDraft({...draft,hairColor:e.target.value})}/></label></div>}
 {appearanceSection==='Corpo'&&<div role="tabpanel" className="avatar-panel"><h4>Proporções reais, apresentação estilizada</h4>{([['height','Altura (cm)',100,230],['weight','Peso (kg)',30,300],['fat','Gordura corporal informada (%)',3,65],['muscle','Volume muscular visual (0–100)',0,100]] as const).map(([key,label,min,max])=><label key={key}>{label}<div className="avatar-measure"><input type="range" min={min} max={max} step="0.1" value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/><input type="number" required min={min} max={max} step="0.1" value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></div></label>)}<p className="avatar-note">A definição visual aumenta com os dias de resultado físico já reconhecidos na sua evolução. O controle define o volume de base. Use Ver anatomia para conferir o corpo sem remover equipamentos. Isso não estima sua massa muscular real.</p></div>}
 {appearanceSection==='Cores'&&<div role="tabpanel" className="avatar-panel"><h4>Paleta do personagem</h4><div className="avatar-colors"><label>Tom de pele<input type="color" value={draft.skin} onChange={e=>setDraft({...draft,skin:e.target.value})}/></label><label>Cor dos olhos<input type="color" value={draft.eyeColor??'#647d91'} onChange={e=>setDraft({...draft,eyeColor:e.target.value})}/></label><label>Cor do cabelo<input type="color" value={draft.hairColor} onChange={e=>setDraft({...draft,hairColor:e.target.value})}/></label></div></div>}
 {appearanceSection==='Prévia'&&<div role="tabpanel" className="avatar-panel"><h4>Criar a partir de uma descrição</h4><label>Descreva sua aparência<textarea maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Homem, 1,80 m, 92 kg, cabelo moderno escuro e barba curta"/></label><button type="button" onClick={()=>{try{const parsed=parseAvatarDescription(description,draft);setDraft(parsed.appearance);setMessage(parsed.matched.length?`${parsed.matched.length} características identificadas. Confira a prévia antes de salvar.`:'Não identifiquei características. Ajuste pelas abas.');}catch(e){setError(e instanceof Error?e.message:'Descrição inválida.');}}}>Aplicar à prévia</button><p className="avatar-note">A descrição altera apenas características explícitas. Medidas continuam sob seu controle.</p></div>}
 <div className="avatar-editor-footer"><span>{busy?'Registrando evolução…':'Prévia atualizada em tempo real'}</span><button className="primary-button" disabled={busy||!account}>{busy?'Salvando…':'Salvar aparência'}</button></div></form>}
 <div hidden={section!=='Criar por Foto'}><AvatarPhotoCreator current={draft} busy={busy} onPreview={appearance=>{setCompare(false);setDraft(appearance);setFocus('rosto');}} onSave={appearance=>action({action:'appearance',appearance})}/></div>
 {account&&section==='Histórico'&&<><h3>Histórico visual</h3>{!account.history.length&&<p>Salve sua aparência para registrar o primeiro marco.</p>}{account.history.slice(0,historyCount).map((h,index)=><button className="avatar-row" key={`${h.at}:${index}`} onClick={()=>setSnapshot(index)}><span>{new Date(h.at).toLocaleDateString('pt-BR')} · {h.appearance.weight} kg</span><span>Visualizar</span></button>)}{account.history.length>historyCount&&<button onClick={()=>setHistoryCount(n=>n+20)}>Ver mais registros</button>}<h3>Extrato de Essência</h3>{!account.transactions.length&&<p>Seu extrato começa na primeira conquista.</p>}{account.transactions.slice().reverse().map(t=><div className="avatar-row" key={t.id}><span>{t.label}<small>{t.at.slice(0,10)}</small></span><strong>{t.amount>0?'+':''}{t.amount}</strong></div>)}</>}
 </div></div></section>;
}
