"use client";

import { Archive, CalendarDays, Check, Circle, Edit3, Flag, MoreVertical, Pause, Play, Plus, Target, Trash2, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { journeyProgress, journeySuggestions, type JourneyRecord } from "@/lib/journeys";

const today = () => new Date().toISOString().slice(0, 10);
const blank = { name: "", category: "", icon: "✦", color: "#c6ff4a", objective: "", startDate: today(), deadline: "", metricName: "Progresso", metricUnit: "%", target: 100, current: 0 };

export function JourneysWorkspace({ journeys, setJourneys, openLegacy }: { journeys: JourneyRecord[]; setJourneys: React.Dispatch<React.SetStateAction<JourneyRecord[]>>; openLegacy: (view: "mapping" | "themes") => void }) {
  const [draft, setDraft] = useState(blank);
  const [editing, setEditing] = useState("");
  const [menu, setMenu] = useState("");
  const [activityJourney, setActivityJourney] = useState("");
  const [activityTitle, setActivityTitle] = useState("");
  const [activityDate, setActivityDate] = useState(today());
  const [activityMinutes, setActivityMinutes] = useState(30);
  const [query, setQuery] = useState("");
  const visible = useMemo(() => journeys.filter((item) => item.status !== "archived" && `${item.name} ${item.category} ${item.objective}`.toLowerCase().includes(query.toLowerCase())), [journeys, query]);

  function save(event: FormEvent) {
    event.preventDefault();
    if (!draft.name.trim() || !draft.category.trim()) return;
    const previous = journeys.find((item) => item.id === editing);
    const now = new Date().toISOString();
    const record: JourneyRecord = { id: previous?.id || `journey-${Date.now()}`, name: draft.name.trim(), category: draft.category.trim(), icon: draft.icon || "✦", color: draft.color, objective: draft.objective.trim(), status: previous?.status || "active", startDate: draft.startDate, deadline: draft.deadline || undefined, metricName: draft.metricName.trim() || "Progresso", metricUnit: draft.metricUnit.trim(), target: Math.max(0, Number(draft.target)), current: Math.max(0, Number(draft.current)), activities: previous?.activities || [], sourceThemeIds: previous?.sourceThemeIds || [], sourceMapIds: previous?.sourceMapIds || [], createdAt: previous?.createdAt || now, updatedAt: now };
    setJourneys((current) => previous ? current.map((item) => item.id === previous.id ? record : item) : [record, ...current]);
    setDraft(blank); setEditing("");
  }
  function edit(item: JourneyRecord) { setEditing(item.id); setDraft({ name: item.name, category: item.category, icon: item.icon, color: item.color, objective: item.objective, startDate: item.startDate, deadline: item.deadline || "", metricName: item.metricName, metricUnit: item.metricUnit, target: item.target, current: item.current }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function addActivity(event: FormEvent) { event.preventDefault(); if (!activityJourney || !activityTitle.trim()) return; setJourneys((current) => current.map((journey) => journey.id === activityJourney ? { ...journey, activities: [...journey.activities, { id: `journey-activity-${Date.now()}`, title: activityTitle.trim(), date: activityDate, minutes: Math.max(1, activityMinutes), done: false }], updatedAt: new Date().toISOString() } : journey)); setActivityTitle(""); }
  function status(item: JourneyRecord, next: JourneyRecord["status"]) { setJourneys((current) => current.map((journey) => journey.id === item.id ? { ...journey, status: next, updatedAt: new Date().toISOString() } : journey)); setMenu(""); }

  return <div className="journeys-page">
    <section className="journey-hero"><div><span className="eyebrow lime">SUA VIDA, SUAS ESCOLHAS</span><h2>Crie qualquer jornada que queira acompanhar.</h2><p>Escolha o esporte, projeto, hábito ou objetivo. Você define como o progresso será medido.</p></div><div className="legacy-links"><button onClick={() => openLegacy("mapping")}>Mapas de estudos preservados</button><button onClick={() => openLegacy("themes")}>Temas preservados</button></div></section>
    <form className="journey-form panel" onSubmit={save}><div className="panel-heading"><div><span className="eyebrow">{editing ? "EDITAR JORNADA" : "NOVA JORNADA"}</span><h3>{editing ? "Atualize sua direção" : "O que você quer construir?"}</h3></div>{editing ? <button type="button" className="icon-button" onClick={() => { setEditing(""); setDraft(blank); }}><X size={17} /></button> : null}</div>
      <div className="journey-form-grid"><label><span>Nome</span><input required value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} placeholder="Ex.: Minha primeira maratona" /></label><label><span>Categoria livre</span><input required list="journey-categories" value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value })} placeholder="Escolha ou escreva outra" /><datalist id="journey-categories">{journeySuggestions.map((item) => <option key={item} value={item} />)}</datalist></label><label><span>Ícone</span><input value={draft.icon} onChange={(e) => setDraft({ ...draft, icon: e.target.value.slice(0, 4) })} /></label><label><span>Cor</span><input type="color" value={draft.color} onChange={(e) => setDraft({ ...draft, color: e.target.value })} /></label><label className="wide-field"><span>Objetivo</span><input value={draft.objective} onChange={(e) => setDraft({ ...draft, objective: e.target.value })} placeholder="Qual resultado você deseja alcançar?" /></label><label><span>Início</span><input type="date" value={draft.startDate} onChange={(e) => setDraft({ ...draft, startDate: e.target.value })} /></label><label><span>Prazo opcional</span><input type="date" value={draft.deadline} onChange={(e) => setDraft({ ...draft, deadline: e.target.value })} /></label><label><span>O que medir</span><input value={draft.metricName} onChange={(e) => setDraft({ ...draft, metricName: e.target.value })} placeholder="Ex.: Quilômetros" /></label><label><span>Unidade</span><input value={draft.metricUnit} onChange={(e) => setDraft({ ...draft, metricUnit: e.target.value })} placeholder="km, páginas, R$..." /></label><label><span>Meta</span><input type="number" min="0" step="any" value={draft.target} onChange={(e) => setDraft({ ...draft, target: Number(e.target.value) })} /></label></div><button className="primary-button"><Plus size={17} /> {editing ? "Salvar jornada" : "Criar jornada"}</button></form>
    {journeys.length ? <form className="journey-activity-form panel" onSubmit={addActivity}><div><span className="eyebrow">PLANEJAR AÇÃO</span><h3>Adicione algo que pretende fazer</h3></div><select required value={activityJourney} onChange={(e) => setActivityJourney(e.target.value)}><option value="">Escolha a jornada</option>{journeys.filter((item) => item.status === "active").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input required value={activityTitle} onChange={(e) => setActivityTitle(e.target.value)} placeholder="Ex.: correr 8 km" /><input type="date" value={activityDate} onChange={(e) => setActivityDate(e.target.value)} /><input type="number" min="1" max="1440" value={activityMinutes} onChange={(e) => setActivityMinutes(Number(e.target.value))} /><button className="outline-button"><CalendarDays size={16} /> Adicionar</button></form> : null}
    <div className="journey-toolbar"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Pesquisar jornadas" /><span>{visible.length} ativa(s)</span></div>
    {visible.length ? <section className="journey-grid">{visible.map((item) => { const progress = journeyProgress(item); return <article className="journey-card panel" key={item.id} style={{ "--journey-color": item.color } as React.CSSProperties}><header><span>{item.icon}</span><div><small>{item.category}</small><h3>{item.name}</h3></div><button onClick={() => setMenu(menu === item.id ? "" : item.id)} aria-label={`Ações de ${item.name}`}><MoreVertical /></button>{menu === item.id ? <div className="card-menu"><button onClick={() => edit(item)}><Edit3 size={14} /> Editar</button>{item.status === "paused" ? <button onClick={() => status(item, "active")}><Play size={14} /> Reativar</button> : <button onClick={() => status(item, "paused")}><Pause size={14} /> Pausar</button>}<button onClick={() => status(item, "completed")}><Check size={14} /> Concluir</button><button onClick={() => status(item, "archived")}><Archive size={14} /> Arquivar</button><button className="danger" onClick={() => { if (window.confirm(`Excluir a jornada “${item.name}”? Os mapas, temas e registros antigos vinculados serão preservados.`)) setJourneys((current) => current.filter((journey) => journey.id !== item.id)); }}><Trash2 size={14} /> Excluir</button></div> : null}</header><p>{item.objective || "Defina o resultado que deseja alcançar."}</p><div className="journey-progress"><div><span>{item.metricName}</span><strong>{item.current} {item.metricUnit} / {item.target} {item.metricUnit}</strong></div><i><b style={{ width: `${progress}%` }} /></i><small>{progress}% concluído</small></div><footer><span><Flag size={14} /> {item.deadline ? new Date(`${item.deadline}T12:00:00`).toLocaleDateString("pt-BR") : "Sem prazo"}</span><span><Target size={14} /> {item.activities.filter((activity) => !activity.done).length} ações pendentes</span></footer></article>; })}</section> : <section className="entity-empty panel"><Target size={28} /><strong>Crie sua primeira jornada</strong><p>Ela pode ser sobre qualquer área escolhida por você.</p></section>}
  </div>;
}

export function TodayWorkspace({ journeys, setJourneys }: { journeys: JourneyRecord[]; setJourneys: React.Dispatch<React.SetStateAction<JourneyRecord[]>> }) {
  const date = today();
  const actions = journeys.flatMap((journey) => journey.activities.filter((activity) => !activity.done && activity.date <= date).map((activity) => ({ journey, activity })));
  function toggle(journeyId: string, activityId: string) { setJourneys((current) => current.map((journey) => journey.id === journeyId ? { ...journey, activities: journey.activities.map((activity) => activity.id === activityId ? { ...activity, done: !activity.done } : activity), updatedAt: new Date().toISOString() } : journey)); }
  return <div className="today-page"><section className="today-hero"><span className="eyebrow lime">HOJE</span><h2>O que você escolheu fazer agora.</h2><p>{actions.length ? `${actions.length} ação(ões) prevista(s) para hoje ou atrasada(s).` : "Seu dia está livre. Adicione ações dentro das suas Jornadas."}</p></section>{actions.length ? <section className="today-list panel">{actions.map(({ journey, activity }) => <button key={activity.id} onClick={() => toggle(journey.id, activity.id)}><Circle /><span style={{ background: journey.color }}>{journey.icon}</span><div><strong>{activity.title}</strong><small>{journey.name} · {activity.minutes} min {activity.date < date ? "· atrasada" : ""}</small></div><Check /></button>)}</section> : <section className="entity-empty panel"><CalendarDays /><strong>Nenhuma ação pendente para hoje</strong><p>Use Jornadas para planejar uma corrida, treino, leitura, estudo ou meta pessoal.</p></section>}</div>;
}
