'use client';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Plus, X, Check, ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-react';
import { complete, due, entryFor, habitFromPreset, habitPresets, habitTemplate, localDate, record, shiftDate, skillPresets, weekDates, weekSummary, type Habit, type RoutineState } from '@/lib/routine';
import type { SkillTrack } from '@/lib/ascension-index';
import { RoutineAssistant } from './routine-assistant';
import { RoutineCalendar } from './routine-calendar';
import './routine.css';
export function RoutineSheet({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const el=dialog.current;const previous=document.activeElement as HTMLElement|null;el?.showModal(); const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el?.close();document.body.style.overflow=overflow;previous?.focus();};},[]);
  return <dialog className="routine-sheet" ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div><header><h3>{title}</h3><button aria-label="Fechar" onClick={onClose}><X size={20}/></button></header>{children}</div></dialog>;
}
export function HabitEditor({habit,tracks,archetypes,onSave,onClose,isNew=false}:{habit:Habit;tracks:SkillTrack[];archetypes:{id:string;name:string}[];onSave:(h:Habit)=>void;onClose:()=>void;isNew?:boolean}) {
  const [h,setH]=useState(habit);const [step,setStep]=useState(0);const [error,setError]=useState('');
  const patch=(p:Partial<Habit>)=>setH({...h,...p});
  return <RoutineSheet title={isNew?'Nova atividade':'Editar atividade'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(step<2){setStep(step+1);return;}if(!h.name.trim()||h.target<=0||h.minutes<1||h.times<1||(h.frequency==='days'&&!h.days.length)||(h.frequency==='once'&&!h.date)){setError('Confira a meta, a duração e os dias selecionados.');return;}onSave({...h,name:h.name.trim()});}}>
    <p className="routine-muted">{step+1} de 3 · {['Atividade','Frequência e meta','Organização'][step]}</p>
    {step===0&&<><label>O que você quer fazer?<input autoFocus required maxLength={120} value={h.name} onChange={e=>patch({name:e.target.value})}/></label><div className="routine-chips">{['Estudar','Correr','Ler','Beber água','Dormir cedo','Meditar'].map(name=><button type="button" key={name} onClick={()=>patch({name})}>{name}</button>)}</div><label>Tipo<select value={h.kind||'habit'} onChange={e=>patch({kind:e.target.value as Habit['kind'],physical:e.target.value==='training'})}><option value="habit">Hábito</option><option value="training">Treino</option><option value="exam">Prova</option></select></label><label>Habilidade relacionada<select value={h.skillId} onChange={e=>patch({skillId:e.target.value})}><option value="">Sem vínculo</option>{tracks.filter(t=>!t.archived).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><p className="routine-muted">A habilidade é o que você desenvolve. Esta atividade é o que você faz.</p></>}
    {step===1&&<><label>Frequência<select value={h.frequency} onChange={e=>patch({frequency:e.target.value as Habit['frequency']})}><option value="daily">Todos os dias</option><option value="days">Dias específicos</option><option value="weekly">X vezes por semana</option><option value="monthly">X vezes por mês</option><option value="once">Uma data específica</option></select></label>{h.frequency==='days'&&<div className="routine-chips">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map((name,i)=><button type="button" aria-pressed={h.days.includes(i)} key={name} onClick={()=>patch({days:h.days.includes(i)?h.days.filter(d=>d!==i):[...h.days,i]})}>{name}</button>)}</div>}{['weekly','monthly'].includes(h.frequency)&&<label>Vezes no período<input type="number" min="1" max={h.frequency==='weekly'?7:31} required value={h.times} onChange={e=>patch({times:Number(e.target.value)})}/></label>}{h.frequency==='once'&&<label>Dia<input required type="date" value={h.date} onChange={e=>patch({date:e.target.value})}/></label>}<div className="routine-fields"><label>Meta<input type="number" min="0.1" step="any" required value={h.target} onChange={e=>patch({target:Number(e.target.value)})}/></label><label>Unidade<input required maxLength={30} value={h.unit} placeholder="km, min, páginas, vez" onChange={e=>patch({unit:e.target.value})}/></label></div><label>Duração estimada (min)<input required type="number" min="1" max="1440" value={h.minutes} onChange={e=>patch({minutes:Number(e.target.value)})}/></label></>}
    {step===2&&<><label>Período<select value={h.period} onChange={e=>patch({period:e.target.value as Habit['period']})}>{['Manhã','Tarde','Noite','Sem horário'].map(p=><option key={p}>{p}</option>)}</select></label><label>Horário opcional<input type="time" value={h.time} onChange={e=>patch({time:e.target.value})}/></label><label>Nome da rotina (opcional)<input maxLength={80} value={h.routine} placeholder="Rotina da manhã" onChange={e=>patch({routine:e.target.value})}/></label><label>Detalhes do treino ou prova<textarea rows={2} value={h.notes||''} onChange={e=>patch({notes:e.target.value})} placeholder="Ex.: membros superiores, 4 séries de 12 repetições"/></label><details><summary>Prioridade e arquétipos</summary><label>Importância (1 a 5)<input type="number" min="1" max="5" value={h.importance} onChange={e=>patch({importance:Number(e.target.value)})}/></label><label className="routine-check"><input type="checkbox" checked={h.physical} onChange={e=>patch({physical:e.target.checked})}/> Atividade física: respeitar dias de recuperação</label>{archetypes.map(a=><label key={a.id}>Contribuição para {a.name}<input type="number" min="0" max="100" value={h.contributions.find(c=>c.id===a.id)?.weight??0} onChange={e=>patch({contributions:[...h.contributions.filter(c=>c.id!==a.id),...(Number(e.target.value)>0?[{id:a.id,weight:Number(e.target.value)}]:[])]})}/></label>)}<small>Pesos relativos. Uma atividade pode contribuir para vários arquétipos.</small></details></>}
    {error&&<p role="alert">{error}</p>}<footer>{step>0&&<button type="button" onClick={()=>setStep(step-1)}>Voltar</button>}<button className="routine-primary" type="submit">{step===2?'Salvar':'Continuar'}</button></footer>
  </form></RoutineSheet>;
}
export function RoutineWorkspace({state,onChange,tracks,onTracksChange,skills,legacy,archetypes}:{state:RoutineState;onChange:(s:RoutineState)=>void;tracks:SkillTrack[];onTracksChange:(tracks:SkillTrack[])=>void;skills:ReactNode;legacy:ReactNode;archetypes:{id:string;name:string}[]}) {
  const [tab,setTab]=useState('Hoje');const [date,setDate]=useState(localDate);const [editing,setEditing]=useState<Habit|null>(null);const [progress,setProgress]=useState<Habit|null>(null);const [amount,setAmount]=useState('');const [menu,setMenu]=useState<Habit|null>(null);const [historyLimit,setHistoryLimit]=useState(50);const [notice,setNotice]=useState('');const [confirm,setConfirm]=useState<Habit|null>(null);
  const list=state.habits.filter(h=>due(h,date,state));const done=list.filter(h=>complete(entryFor(state,h.id,date))).length;const week=weekDates(date);const summary=weekSummary(state,date);
  const save=(h:Habit)=>{onChange({...state,habits:state.habits.some(a=>a.id===h.id)?state.habits.map(a=>a.id===h.id?h:a):[...state.habits,h]});setEditing(null);setNotice('Atividade salva.');};
  const mark=(h:Habit)=>{const current=entryFor(state,h.id,date);onChange(record(state,h,date,complete(current)?0:(current?.target??h.target)));setNotice(complete(current)?'Atividade marcada como pendente.':'Atividade concluída.');};
  const row=(h:Habit)=><article className="routine-row" key={h.id}><button className="routine-tick" aria-label={`${complete(entryFor(state,h.id,date))?'Desmarcar':'Concluir'} ${h.name}`} aria-pressed={complete(entryFor(state,h.id,date))} onClick={()=>mark(h)}>{complete(entryFor(state,h.id,date))?<Check size={20}/>:<span/>}</button><button className="routine-row-copy" onClick={()=>{setProgress(h);setAmount(String(entryFor(state,h.id,date)?.value??0));}}><strong>{h.kind==='exam'?'Prova · ':h.kind==='training'?'Treino · ':''}{h.name}</strong><small>{h.time&&`${h.time} · `}{entryFor(state,h.id,date)?.value??0} / {entryFor(state,h.id,date)?.target??h.target} {h.unit}{h.routine&&` · ${h.routine}`}{h.notes&&` · ${h.notes}`}</small><progress max={entryFor(state,h.id,date)?.target??h.target} value={entryFor(state,h.id,date)?.value??0}/></button><button aria-label={`Ações de ${h.name}`} onClick={()=>setMenu(h)}><MoreHorizontal size={20}/></button></article>;
  return <section className="routine-area"><header className="routine-heading"><div><span className="eyebrow">EXECUÇÃO</span><h2>Rotina</h2></div><button className="routine-primary" onClick={()=>setEditing(habitTemplate('',date))}><Plus size={18}/> Novo hábito</button></header><nav className="routine-tabs" aria-label="Rotina">{['Hoje','Calendário','Semana','Hábitos','Habilidades','Planejar com IA','Histórico'].map(t=><button key={t} aria-current={t===tab?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav><p role="status" className="routine-status">{notice}</p>
    {tab==='Calendário'&&<RoutineCalendar state={state} onDay={day=>{setDate(day);setTab('Hoje');}}/>}
    {tab==='Hoje'&&<div className="routine-presets"><strong>Comece com um modelo</strong><div>{habitPresets.map(preset=><button key={preset.name} onClick={()=>setEditing(habitFromPreset(preset,date))}>{preset.name}</button>)}</div></div>}
    {tab==='Hoje'&&<><div className="routine-date"><button aria-label="Dia anterior" onClick={()=>setDate(shiftDate(date,-1))}><ChevronLeft/></button><label>Dia<input type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><button aria-label="Próximo dia" onClick={()=>setDate(shiftDate(date,1))}><ChevronRight/></button></div><h3>{done} de {list.length} atividades concluídas</h3><progress aria-label="Progresso diário" max={list.length||1} value={done}/>{!list.length&&<p>Nenhuma atividade para este dia. Crie um hábito ou adicione uma sugestão da Ascensão.</p>}{(['Manhã','Tarde','Noite','Sem horário'] as const).map(p=>{const activities=list.filter(h=>h.period===p);return activities.length?<section key={p}><h3>{p}</h3>{activities.map(row)}</section>:null;})}<details><summary>Atividades das jornadas existentes</summary>{legacy}</details></>}
    {tab==='Planejar com IA'&&<RoutineAssistant state={state} onChange={onChange} tracks={tracks}/>}
    {tab==='Semana'&&<><h3>{summary.done} / {summary.target} · {summary.percent}% da semana</h3><p className="routine-muted">Metas mensais aparecem como oportunidades de execução; o total considera esta semana.</p><div className="routine-week">{week.map(d=><button key={d} onClick={()=>{setDate(d);setTab('Hoje');}}><strong>{new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short',day:'numeric'})}</strong>{state.habits.filter(h=>due(h,d,state)).map(h=><span key={h.id}>{complete(entryFor(state,h.id,d))?'✓':'○'} {h.name}</span>)}</button>)}</div><section><h3>Check-in semanal</h3><p>{summary.done?`Você concluiu ${summary.done} atividades previstas.`:'Ainda não há conclusões nesta semana.'}</p>{state.habits.filter(h=>!h.archived).map(h=>{const missed=week.filter(d=>d<localDate()&&due(h,d,state)&&!complete(entryFor(state,h.id,d))).length;return missed>=3?<article className="routine-row" key={h.id}><p>{h.name} ficou pendente em {missed} dias. Quer ajustar a duração de {h.minutes} para {Math.max(5,Math.round(h.minutes/2))} minutos?</p><button onClick={()=>setEditing({...h,minutes:Math.max(5,Math.round(h.minutes/2))})}>Ajustar</button></article>:null;})}</section></>}
    {tab==='Hábitos'&&<>{state.habits.filter(h=>!h.archived).map(row)}{!state.habits.length&&<p>Escolha o que quer desenvolver. Nenhuma rotina é obrigatória.</p>}<details><summary>Arquivados</summary>{state.habits.filter(h=>h.archived).map(h=><article className="routine-row" key={h.id}><strong>{h.name}</strong><button onClick={()=>save({...h,archived:false})}>Reativar</button></article>)}</details></>}
    {tab==='Habilidades'&&<div className="routine-presets"><strong>Habilidades sugeridas</strong><p className="routine-muted">Adicione uma base e ajuste sua meta antes de registrar resultados.</p><div>{skillPresets.filter(name=>!tracks.some(track=>track.name===name&&!track.archived)).map(name=><button key={name} onClick={()=>onTracksChange([...tracks,{id:crypto.randomUUID(),name,domain:['Condicionamento físico','Força'].includes(name)?'Corpo':'Intelecto',unit:'pontos',direction:'higher',context:'Predefinição editável',journeyId:'',weeklyDays:3,mission:'Praticar e registrar resultados',baseline:0,target:100,referenceUrl:'',referenceDate:'',evidence:[],archived:false}])}>{name}</button>)}</div></div>}
    {tab==='Habilidades'&&<><p>Hábitos registram execução. Níveis de habilidade dependem de resultados registrados.</p>{tracks.filter(t=>!t.archived).map(t=>{const linked=state.habits.filter(h=>h.skillId===t.id&&!h.archived);const recent=state.entries.filter(e=>week.includes(e.date)&&linked.some(h=>h.id===e.habitId));const totals=recent.reduce<Record<string,number>>((acc,e)=>({...acc,[e.unit]:(acc[e.unit]||0)+e.value}),{});return <details key={t.id}><summary>{t.name} · {linked.length} atividades</summary><p>Esta semana: {recent.filter(complete).length} conclusões. {Object.entries(totals).map(([unit,value])=>`${value} ${unit}`).join(' · ')}</p>{linked.map(row)}{!linked.length&&<p>Vincule um hábito a esta habilidade no formulário de criação.</p>}</details>;})}{skills}</>}
    {tab==='Histórico'&&<>{!state.entries.length&&<p>Seus registros aparecerão aqui.</p>}{[...state.entries].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,historyLimit).map(e=><article className="routine-row" key={`${e.habitId}:${e.date}`}><div><strong>{e.name}</strong><p>{e.date} · {e.value}/{e.target} {e.unit} · {complete(e)?'Concluído':'Em progresso'}</p></div><button onClick={()=>{setDate(e.date);setTab('Hoje');}}>Abrir dia</button></article>)}</>}
    {tab==='Histórico'&&state.entries.length>historyLimit&&<button onClick={()=>setHistoryLimit(historyLimit+50)}>Carregar mais registros</button>}
    {editing&&<HabitEditor habit={editing} tracks={tracks} archetypes={archetypes} onSave={save} onClose={()=>setEditing(null)} isNew={!state.habits.some(h=>h.id===editing.id)}/>}
    {progress&&<RoutineSheet title={`Progresso · ${progress.name}`} onClose={()=>setProgress(null)}><form onSubmit={e=>{e.preventDefault();onChange(record(state,progress,date,Number(amount)));setProgress(null);setNotice('Progresso salvo.');}}><label>Quantidade acumulada ({progress.unit})<input autoFocus required type="number" min="0" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="routine-primary">Salvar progresso</button></form></RoutineSheet>}
    {menu&&<RoutineSheet title={menu.name} onClose={()=>setMenu(null)}><div className="routine-menu"><button onClick={()=>{setEditing(menu);setMenu(null);}}>Editar / mover para outro dia</button><button onClick={()=>{save({...menu,id:crypto.randomUUID(),name:`${menu.name} (cópia)`,created:localDate()});setMenu(null);}}>Duplicar</button>{[-1,1].map(delta=><button key={delta} onClick={()=>{const habits=[...state.habits];const i=habits.findIndex(h=>h.id===menu.id);const j=i+delta;if(j>=0&&j<habits.length){[habits[i],habits[j]]=[habits[j],habits[i]];onChange({...state,habits});}setMenu(null);}}>{delta<0?'Mover para cima':'Mover para baixo'}</button>)}<button onClick={()=>{setConfirm(menu);setMenu(null);}}>Arquivar / remover da rotina</button></div></RoutineSheet>}
    {confirm&&<RoutineSheet title={`Arquivar ${confirm.name}?`} onClose={()=>setConfirm(null)}><p>A atividade deixa de aparecer na rotina. Histórico, XP e resultados anteriores serão preservados.</p><button onClick={()=>{save({...confirm,archived:true});setConfirm(null);}}>Confirmar arquivamento</button></RoutineSheet>}
  </section>;
}
